version: "3.8"
services:
  
  # mainclient:
  #   build: ./mainclient/
  #   hostname: mainclient
  #   ports:
  #     - 80:80
  #   networks: 
  #     - main_network
  
  firego:
    image: tmprimitivo/firego
    hostname: firego
    ports:
      - 5000:5000
    networks: 
      - main_network
    
  gocompose:
    build: ./GoCompose/
    privileged: true
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./GoCompose/composefiles:/app/composefiles
      - ./GoCompose/scripts:/app/scripts
    environment:
      - MODE=COMPOSE
      - "PROJPWD=${PWD}"
    hostname: gocompose
    ports:
      - 1997:1997
    networks: 
      - main_network
      
networks:
  main_network:
    driver: bridge